[package]
name = "nayland"
version = "0.1.0"
license = "BSD-3-Clause"
kind = "Library"
backend = "C"
binaries = []

[toolchain]
version = "2.2.0"

[dependencies]
shakar = ">= 0.1.3"
pretty = ">= 0.2.0"

[platforms.native]
link = ["wayland-client"]
include = ["wayland-client"]
